version: '3'
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: hmnodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - '11610:11600'
    volumes:
      - '.:/home/node/app'
      - 'node_modules:/home/node/app/node_modules'
    networks:
      - apphm-network
    command: './wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/nodemon app.js'
  db:
    image: 'mongo:latest'
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - 'mongodb-data:/data/db'
    networks:
      - apphm-network
networks:
  apphm-network:
    driver: bridge
volumes:
  mongodb-data: 
  node_modules: 
